// Generated by CoffeeScript 2.5.1
(function() {
  var Modules;

  Modules = {
    cliargumentsmodule: require("./cliargumentsmodule"),
    configmodule: require("./configmodule"),
    debugmodule: require("./debugmodule"),
    mainprocessmodule: require("./mainprocessmodule"),
    startupmodule: require("./startupmodule")
  };

  module.exports = Modules;

}).call(this);
