// Generated by CoffeeScript 2.5.1
(function() {
  var cfg, log, mainprocessmodule, olog, ostr, pathHandler, preparation, print;

  mainprocessmodule = {
    name: "mainprocessmodule"
  };

  //###########################################################
  //region logPrintFunctions
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["mainprocessmodule"] != null) {
      console.log("[mainprocessmodule]: " + arg);
    }
  };

  olog = function(o) {
    return log("\n" + ostr(o));
  };

  ostr = function(o) {
    return JSON.stringify(o, null, 4);
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion

  //###########################################################
  cfg = null;

  pathHandler = null;

  preparation = null;

  //###########################################################
  mainprocessmodule.initialize = function() {
    log("mainprocessmodule.initialize");
    cfg = allModules.configmodule;
    pathHandler = allModules.pathhandlermodule;
    preparation = allModules.preparationmodule;
  };

  
  //###########################################################
  mainprocessmodule.execute = async function(e) {
    log("mainprocessmodule.execute");
    await pathHandler.preparePathsOfUnprepared(e.unprepared);
    await pathHandler.preparePathsOfContent(e.content);
    await pathHandler.checkOutputPath(e.output);
    await preparation.execute();
  };

  module.exports = mainprocessmodule;

}).call(this);
